// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQTysB8n52DKO0-WqQu--qH4If6Nilk4M',
    appId: '1:92344634238:web:0bf7bb91914f09acbb812f',
    messagingSenderId: '92344634238',
    projectId: 'practice-app-a5f55',
    authDomain: 'practice-app-a5f55.firebaseapp.com',
    storageBucket: 'practice-app-a5f55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdNTYNJEq5LCydmn4UhAagltNZbT-q_PM',
    appId: '1:92344634238:android:8ca2f5910975a105bb812f',
    messagingSenderId: '92344634238',
    projectId: 'practice-app-a5f55',
    storageBucket: 'practice-app-a5f55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCers_F5PmC5TChU-PllWURvwkyZILRPTo',
    appId: '1:92344634238:ios:f1259d6500ab22a5bb812f',
    messagingSenderId: '92344634238',
    projectId: 'practice-app-a5f55',
    storageBucket: 'practice-app-a5f55.appspot.com',
    iosBundleId: 'com.example.backgroundApp',
  );

}